name: Deploy Website via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.212.215.85
          username: root
          key: ${{ secrets.SECRETDHA }}
          port: 22
          script: |
            whoami
            pwd

      - name: Deploy Website
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 13.212.215.85
          username: root
          key: ${{ secrets.SECRETDHA }}
          port: 22
          source: "."
          target: "/www/wwwroot/dhammika.run.place"

      - name: Verify Files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.212.215.85
          username: root
          key: ${{ secrets.SECRETDHA }}
          port: 22
          script: |
            ls -la /www/wwwroot/dhammika.run.place

      - name: Set Permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.212.215.85
          username: root
          key: ${{ secrets.SECRETDHA }}
          port: 22
          script: |
            chmod -R 755 /www/wwwroot/dhammika.run.place
